USE DataWarehouseAnalytics;

/* Business problem: How can we increase revenue? */

/* Here I retrieve customer behaviour with a CTE which includes details such as customer name, date of first order, 
date of last order and total spending. 
I also create a CTE that shows customer behaviour and segments customers into 3 categories (VIP, Regular, New):

	- VIP: Customers  with at least 12 months history whose spending is greater than 5,000
	- Regular: Customers with at least 12 months history, whose spending is less than or equal to 5,000
	- New: Customers with a lifepsan of less than 12 months

I use the CTE's to make the following calculations:
	1. Number of customers by segment
	2. Total Revenue by segment 
	3. Average Order Value (AOV) by segment */

-- Customer behaviour
WITH CTE_customer_behaviour AS (
	SELECT 
	s.order_number,
	s.sales_amount,
	s.customer_key,
	s.order_date,
	c.first_name,
	c.last_name,
	MIN(s.order_date) OVER(PARTITION BY s.customer_key) first_order,
	MAX(s.order_date) OVER(PARTITION BY s.customer_key) last_order,
	DATEDIFF(month, MIN(s.order_date) OVER(PARTITION BY s.customer_key), MAX(s.order_date) OVER(PARTITION BY s.customer_key)) order_history_months,
	SUM(s.sales_amount) OVER(PARTITION BY s.customer_key) total_spending
	FROM gold.fact_sales s
	LEFT JOIN gold.dim_customers c
	ON S.customer_key = c.customer_key
)

-- Total number of orders by customer
, CTE_customer_order_distinct_count AS (
SELECT customer_key,
COUNT(DISTINCT order_number) total_orders
FROM CTE_customer_behaviour
GROUP BY customer_key
)

-- A step in calculating average order value
, CTE_customer_avg_ord_value AS (
SELECT 
	order_number,
	sales_amount,
	b.customer_key,
	order_date,
	first_name,
	last_name,
	first_order,
	last_order,
	order_history_months,
	total_spending,
	d.total_orders
	FROM CTE_customer_behaviour b
	LEFT JOIN CTE_customer_order_distinct_count d
	ON b.customer_key = d.customer_key
)

-- A step in making the final customer segments CTE
, CTE_customer_segments_intermediate AS (
	SELECT 
	b.customer_key,
	b.first_name,
	b.last_name, 
	b.order_history_months,
	o.total_orders,
	b.total_spending,
	CASE WHEN b.order_history_months >= 12 AND b.total_spending > 5000
		THEN 'VIP'
		WHEN b.order_history_months >= 12 AND b.total_spending <= 5000
		THEN 'Regular'
		WHEN b.order_history_months < 12
		THEN 'New'
		WHEN b.order_date IS NULL
		THEN 'unknown'
		END AS customer_segment	
	FROM CTE_customer_behaviour b
	LEFT JOIN CTE_customer_avg_ord_value o on
	b.customer_key = o.customer_key
)

-- Final Customer behaviour and segments CTE
, CTE_customer_segments AS (
SELECT 
	customer_key,
	first_name,
	last_name, 
	order_history_months,
	total_orders,
	total_spending,
	customer_segment
FROM (
SELECT 
	customer_key,
	first_name,
	last_name, 
	order_history_months,
	total_orders,
	total_spending,
	customer_segment,
	ROW_NUMBER() OVER(PARTITION BY customer_key ORDER BY customer_key) row_n_flag -- filtering out duplicate rows
	FROM CTE_customer_segments_intermediate
	)t
WHERE row_n_flag = 1
)

-- Number of customers by segment
, CTE_segment_numbers AS (
SELECT 
customer_segment,
COUNT(DISTINCT customer_key) customers 
FROM CTE_Customer_segments
GROUP BY customer_segment
)

----------------------------------------------------------
----------------------------------------------------------
-- Business focused questions

-- 1. How many customers are in each segment? 
-- 2. What's the percentage contribution of revenue generated by each segment?
-- 3. What's the average order value by each segment?

/* --------------------------------------------------------------------
-- 1. Number of customers by segment and percentage contribution
--------------------------------------------------------------------*/
SELECT 
customer_segment, 
customers,
ROUND((CAST(customers AS FLOAT) / CAST(SUM(customers) OVER() AS FLOAT)) * 100, 1) 'percent_contribution'
FROM CTE_segment_numbers
WHERE customer_segment != 'unknown'
ORDER BY customers DESC;

-- Insight: 80% of are New and only 9% are VIP

/* --------------------------------------------------------------------
-- 2. Total Revenue by segment and percentage contribution
--------------------------------------------------------------------*/
SELECT 
customer_segment,
revenue_by_segment,
ROUND((CAST(revenue_by_segment AS FLOAT) / CAST(SUM(revenue_by_segment) OVER() AS FLOAT)) * 100, 1) 'percent_contribution'
FROM (
SELECT 
customer_segment,
SUM(total_spending) revenue_by_segment
FROM CTE_customer_segments
WHERE customer_segment != 'unknown'
GROUP BY customer_segment)t
ORDER BY 3 DESC

/* Insight: Although VIP only makes up 9% of customers, VIP customers generated about the same revenue as the New customers (which are the majority)
VIP's are clearly generating more revenue per customer */

/* --------------------------------------------------------------------
-- 2. Average Order Value (AOV) by segment and percentage contribution
--------------------------------------------------------------------*/
SELECT
customer_segment,
AOV,
ROUND(CAST(AOV AS FLOAT)/CAST(SUM(AOV) OVER() AS FLOAT) * 100, 1) 'percent_contribution'
FROM (
SELECT 
	customer_segment,
	SUM(total_spending)/SUM(total_orders) AOV 
	FROM CTE_customer_segments
	WHERE customer_segment != 'unknown'
	GROUP BY customer_segment)t
ORDER BY AOV DESC

-- Insight: By far, VIP customers have a very high Average Order Value, making up over 50% of the Average Order Value 

/* Summary:
Revenue concentration lies in VIP customers. 

Aims: 
1. VIP: Retain customers
2. Regular: Upsell to VIP
3. New: Retain

We want to increase customer retention to increase revenue
*/
